import { useQuery } from '@tanstack/react-query'
import api from '../api/client.js'
import ActionTimeline from '../components/ActionTimeline.jsx'

function useProductNames() {
  const { data } = useQuery({
    queryKey: ['products'],
    queryFn: () => api.get('/api/products').then((r) => r.data),
  })
  const names = {}
  ;(data || []).forEach((p) => {
    names[p.id] = p.name
  })
  return names
}

export default function MorningBrief() {
  const productNames = useProductNames()

  const { data: brief } = useQuery({
    queryKey: ['brief'],
    queryFn: () => api.get('/api/brief/morning').then((r) => r.data),
  })

  const { data: actions } = useQuery({
    queryKey: ['actions'],
    queryFn: () => api.get('/api/actions').then((r) => r.data),
  })

  return (
    <div>
      <div className="bg-gradient-to-r from-indigo-600 to-violet-600 text-white rounded-xl p-6 mb-6 shadow">
        <h1 className="text-2xl font-bold">MarketMind worked while you slept 🌙</h1>
        <p className="text-indigo-100 mt-1">
          {brief?.date} · {brief?.totalActions ?? 0} actions ·{' '}
          {brief?.executedCount ?? 0} executed · {brief?.blockedCount ?? 0} blocked
        </p>
      </div>

      <div className="bg-white rounded-xl border border-slate-200 shadow-sm p-6 mb-6">
        <div className="flex items-center justify-between mb-3">
          <h2 className="font-bold text-slate-900">This morning's brief</h2>
          {brief?.source && (
            <span className="text-xs px-2 py-0.5 rounded bg-slate-100 text-slate-500">
              {brief.source === 'LIVE' ? 'Generated by Kimi' : 'Rule-based summary'}
            </span>
          )}
        </div>
        <p className="text-slate-700 whitespace-pre-line leading-relaxed">
          {brief?.narrative || 'No brief available yet.'}
        </p>
      </div>

      <div className="bg-white rounded-xl border border-slate-200 shadow-sm p-6">
        <h2 className="font-bold text-slate-900 mb-4">Overnight activity</h2>
        <ActionTimeline actions={actions} productNames={productNames} />
      </div>
    </div>
  )
}
