package com.marketmind.service;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.node.ArrayNode;
import com.fasterxml.jackson.databind.node.ObjectNode;
import com.marketmind.dto.MorningBriefDto;
import com.marketmind.model.ActionLog;
import com.marketmind.model.Product;
import com.marketmind.repository.ActionLogRepository;
import com.marketmind.repository.ProductRepository;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Service;

import java.time.LocalDate;
import java.util.List;
import java.util.Map;
import java.util.function.Function;
import java.util.stream.Collectors;

/**
 * Generates the seller's morning brief from the overnight action log. Uses Kimi
 * prose (temperature 0.7) when configured, otherwise a warm rule-based
 * narrative. The result is cached until {@link #regenerate()} is called so the
 * dashboard's repeated GETs don't re-hit the model.
 */
@Service
public class MorningBriefService {

    private static final Logger log = LoggerFactory.getLogger(MorningBriefService.class);

    private static final String BRIEF_PROMPT_HEADER = """
            You are MarketMind. Write a morning brief for the seller based on the overnight activity log below.

            Format:
            1. One opening sentence summarising overnight market conditions (2-3 key signals)
            2. A numbered list of decisions made, each with: what happened in the market, what you did, why
            3. One closing sentence: what to watch today

            Write in warm, plain English. The seller is not technical. Be specific with numbers.
            If guardrail blocks occurred, mention them positively ("your rules protected your margins").

            Activity log:
            """;

    private final ActionLogRepository actionLogRepo;
    private final ProductRepository productRepo;
    private final KimiClient kimi;
    private final ObjectMapper mapper;

    private volatile MorningBriefDto cached;

    public MorningBriefService(ActionLogRepository actionLogRepo,
                               ProductRepository productRepo,
                               KimiClient kimi,
                               ObjectMapper mapper) {
        this.actionLogRepo = actionLogRepo;
        this.productRepo = productRepo;
        this.kimi = kimi;
        this.mapper = mapper;
    }

    /** Today's brief, generating (and caching) it on first access. */
    public MorningBriefDto getMorningBrief() {
        MorningBriefDto local = cached;
        if (local == null) {
            local = regenerate();
        }
        return local;
    }

    /** Force a fresh brief from the current action log. */
    public synchronized MorningBriefDto regenerate() {
        List<ActionLog> entries = actionLogRepo.findAllByOrderByCreatedAtDesc();
        Map<String, String> productNames = productRepo.findAll().stream()
                .collect(Collectors.toMap(Product::getId, Product::getName, (a, b) -> a));

        int executed = (int) entries.stream().filter(e -> Boolean.TRUE.equals(e.getExecuted())).count();
        int blocked = (int) entries.stream().filter(e -> Boolean.TRUE.equals(e.getGuardrailBlocked())).count();

        String narrative;
        String source;
        if (kimi.isConfigured() && !entries.isEmpty()) {
            try {
                narrative = kimi.chat("You are MarketMind, a warm and trustworthy business advisor.",
                        BRIEF_PROMPT_HEADER + buildActivityJson(entries, productNames), 0.7);
                source = "LIVE";
                log.info("[LIVE] Morning brief generated by Kimi from {} action(s)", entries.size());
            } catch (Exception e) {
                log.warn("[LIVE] Kimi morning brief failed ({}). Falling back to rule-based narrative.",
                        e.getMessage());
                narrative = ruleBasedNarrative(entries, productNames, executed, blocked);
                source = "MOCK";
            }
        } else {
            narrative = ruleBasedNarrative(entries, productNames, executed, blocked);
            source = "MOCK";
            log.info("[MOCK] Morning brief generated from {} action(s)", entries.size());
        }

        cached = new MorningBriefDto(LocalDate.now(), entries.size(), executed, blocked, narrative, source);
        return cached;
    }

    private String buildActivityJson(List<ActionLog> entries, Map<String, String> productNames) {
        ArrayNode arr = mapper.createArrayNode();
        for (ActionLog e : entries) {
            ObjectNode n = arr.addObject();
            n.put("timestamp", String.valueOf(e.getCreatedAt()));
            n.put("product", productNames.getOrDefault(e.getProductId(), e.getProductId()));
            n.put("action_type", String.valueOf(e.getActionType()));
            n.put("from_value", e.getFromValue());
            n.put("to_value", e.getToValue());
            n.put("executed", Boolean.TRUE.equals(e.getExecuted()));
            n.put("guardrail_blocked", Boolean.TRUE.equals(e.getGuardrailBlocked()));
            if (e.getBlockReason() != null) {
                n.put("block_reason", e.getBlockReason());
            }
            if (e.getKimiExplanation() != null) {
                n.put("explanation", e.getKimiExplanation());
            }
        }
        return arr.toPrettyString();
    }

    private String ruleBasedNarrative(List<ActionLog> entries,
                                      Map<String, String> productNames,
                                      int executed, int blocked) {
        if (entries.isEmpty()) {
            return "Good morning. It was a quiet night — no market moves crossed your action thresholds, "
                    + "so nothing was changed. I'll keep watching your competitors and the social signals today.";
        }

        StringBuilder sb = new StringBuilder();
        sb.append("Good morning. While you slept, MarketMind made ").append(executed)
                .append(executed == 1 ? " move" : " moves")
                .append(" across your store");
        if (blocked > 0) {
            sb.append(", and your guardrails stepped in ").append(blocked)
                    .append(blocked == 1 ? " time" : " times")
                    .append(" to protect your margins");
        }
        sb.append(".\n\n");

        // Oldest-first reads more naturally as a timeline.
        List<ActionLog> chrono = entries.stream()
                .sorted((a, b) -> a.getCreatedAt().compareTo(b.getCreatedAt()))
                .toList();
        int i = 1;
        for (ActionLog e : chrono) {
            String name = productNames.getOrDefault(e.getProductId(), e.getProductId());
            sb.append(i++).append(". ").append(name).append(" — ").append(humanAction(e));
            String detail = Boolean.TRUE.equals(e.getGuardrailBlocked())
                    ? e.getBlockReason()
                    : e.getKimiExplanation();
            if (detail != null && !detail.isBlank()) {
                sb.append(" ").append(detail);
            }
            sb.append("\n");
        }

        sb.append("\nToday, keep an eye on your competitors' restocking and whether the social buzz holds. "
                + "I'll stay on watch and only act within the limits you've set.");
        return sb.toString();
    }

    private String humanAction(ActionLog e) {
        String verb = switch (String.valueOf(e.getActionType())) {
            case "MODE_TRANSITION" -> "switched mode " + e.getFromValue() + " → " + e.getToValue() + ".";
            case "PRICE_UPDATE" -> Boolean.TRUE.equals(e.getGuardrailBlocked())
                    ? "a price move to $" + e.getToValue() + " was blocked."
                    : "price moved $" + e.getFromValue() + " → $" + e.getToValue() + ".";
            case "AD_BID_UPDATE" -> "ad bid moved $" + e.getFromValue() + " → $" + e.getToValue() + ".";
            default -> "no action taken.";
        };
        return verb;
    }
}
